package Selenium;// Generated by Selenium IDE
import au.com.bytecode.opencsv.CSVWriter;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.io.BufferedWriter;


public class Example2 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void example() throws IOException {
        driver.get("https://play.google.com/store/apps/details?id=app.spidy.spidy&gl=GB&showAllReviews=true");
        driver.manage().window().setSize(new Dimension(1050, 660));
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        List<WebElement> reviews = driver.findElements(By.xpath("//div[@class='UD7Dzf']"));
        List<String> list = new ArrayList<>();
        for (WebElement webElement : reviews) {
            String review = webElement.getText();
            review = review.replaceAll(",","");
//            System.out.println(review);
            list.add(review);
        }
        List<String> list2 = new ArrayList<>();
        for (int i=0;i<(list.size()*0.5 -1) ;i++){
            String hing = list.get(2*i);
            list2.add(hing);
            String thing = list.get((2*i) +1);
            list2.add(thing);
            list2.add(hing);
            list2.add(thing);
        }
        for(int i=0;i<list2.size();i++){
            System.out.println(list2.get(i));
        }
//        File file = new File("test.csv");
//        FileWriter fw = new FileWriter(file);
//        BufferedWriter bw = new BufferedWriter(fw);
//        bw.write("Domain");
//        bw.newLine();
//        for(int i=0;i<list.size();i++)
//        {
//            bw.write(list.get(i+1)+","+list.get(i++));
//            bw.newLine();
//        }
//        bw.close();
//        fw.close();
    }
}
