package Selenium;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class ThirdSiteTogeather {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void example() throws IOException {
        driver.get("https://play.google.com/store/apps/details?id=app.spidy.spidy&gl=GB&showAllReviews=true");
        driver.manage().window().setSize(new Dimension(1050, 660));
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        List<WebElement> reviews = driver.findElements(By.xpath("//div[@class='UD7Dzf']"));
        List<String> list = new ArrayList<>();
        for (WebElement webElement : reviews) {
            String review = webElement.getText();
            System.out.println(review);
            list.add(review);
        }
        FileWriter writer = new FileWriter("output8.txt");
        for(String str: list) {
            writer.write(str + System.lineSeparator() + System.lineSeparator() +System.lineSeparator());
        }
        writer.close();

        driver.manage().window().setSize(new Dimension(1050, 660));
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        List<WebElement> reviews2 = driver.findElements(By.xpath("//*[@class=\"pf5lIe\"]/div"));
        List<String> list2 = new ArrayList<>();
        for (WebElement webElement : reviews2) {
            String review = webElement.getAttribute("aria-label");
            System.out.println(review);
            list2.add(review);
        }
        FileWriter writer2 = new FileWriter("output7.txt");
        for(String str: list2) {
            writer2.write(str + System.lineSeparator() + System.lineSeparator());
        }
        writer2.close();

        driver.manage().window().setSize(new Dimension(1050, 660));
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        List<WebElement> reviews3 = driver.findElements(By.xpath("//span[@class='p2TkOb']"));
        List<String> list3 = new ArrayList<>();
        for (WebElement webElement : reviews3) {
            String review = webElement.getText();
            System.out.println(review);
            list3.add(review);
        }
        FileWriter writer3 = new FileWriter("output23.txt");
        for(String str: list3) {
            writer3.write(str + System.lineSeparator() + System.lineSeparator());
        }
        writer3.close();
    }
}