package Selenium;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class ThirdSite {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void example() throws IOException {
        driver.get("https://play.google.com/store/apps/details?id=app.spidy.spidy&gl=GB&showAllReviews=true");
        driver.manage().window().setSize(new Dimension(1050, 660));
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        List<WebElement> reviews = driver.findElements(By.xpath("//div[@class='UD7Dzf']"));
        List<String> list = new ArrayList<>();
        for (WebElement webElement : reviews) {
            String review = webElement.getText();
            System.out.println(review);
            list.add(review);
        }
        FileWriter writer = new FileWriter("output8.txt");
        for(String str: list) {
            writer.write(str + System.lineSeparator() + System.lineSeparator() +System.lineSeparator());
        }
        writer.close();
    }
    @Test
    public void example3() throws IOException {
        driver.get("https://play.google.com/store/apps/details?id=app.spidy.spidy&gl=GB&showAllReviews=true");
        driver.manage().window().setSize(new Dimension(1050, 660));
        driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
        List<WebElement> reviews = driver.findElements(By.xpath("//*[@class=\"pf5lIe\"]/div"));
        List<String> list = new ArrayList<>();
        for (WebElement webElement : reviews) {
            String review = webElement.getAttribute("aria-label");
            System.out.println(review);
            list.add(review);
        }
        FileWriter writer = new FileWriter("output7.txt");
        for(String str: list) {
            writer.write(str + System.lineSeparator() + System.lineSeparator());
        }
        writer.close();
    }
    @Test
    public void example4() throws IOException {
        driver.get("https://play.google.com/store/apps/details?id=app.spidy.spidy&gl=GB&showAllReviews=true");
        driver.manage().window().setSize(new Dimension(1050, 660));
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        List<WebElement> reviews = driver.findElements(By.xpath("//span[@class='p2TkOb']"));
        List<String> list = new ArrayList<>();
        for (WebElement webElement : reviews) {
            String review = webElement.getText();
            System.out.println(review);
            list.add(review);
        }
        FileWriter writer = new FileWriter("output23.txt");
        for(String str: list) {
            writer.write(str + System.lineSeparator() + System.lineSeparator());
        }
        writer.close();
    }
}

